var mongoose = require('mongoose');

var tblspecs = new mongoose.Schema({
    brand: {type:String},
    model: {type:String},
    network_technology: {type:String},
    twoG_bands: {type:String},
    threeG_bands: {type:String},
    fourG_bands: {type:String},
    network_speed: {type:String},
    GPRS: {type:String},
    EDGE: {type:String},
    announced: {type:String},
    status: {type:String},
    dimentions: {type:String},
    weight_g: {type:String},
    weight_oz: {type:String},
    SIM: {type:String},
    display_type: {type:String},
    display_resolution: {type:String},
    display_size: {type:String},
    OS: {type:String},
    CPU: {type:String},
    Chipset: {type:String},
    GPU: {type:String},
    memory_card: {type:String},
    internal_memory: {type:String},
    RAM: {type:String},
    primary_camera: {type:String},
    secondary_camera: {type:String},
    loud_speaker: {type:String},
    audio_jack: {type:String},
    WLAN: {type:String},
    bluetooth: {type:String},
    GPS: {type:String},
    NFC: {type:String},
    radio: {type:String},
    USB: {type:String},
    sensors: {type:String},
    battery: {type:String},
    colors: {type:String},
    approx_price_EUR: {type:Number},
    date: {type:Date},
    img_url: {type:String},
});

module.exports = mongoose.model('tblspecs',tblspecs);